server:
  port: 8080
  # 스프링부트가 종료 요청을 받았을 때 현재 본인이 하던 일(요청에 대한 응답, 배치작업 등)을 전부 마친 후 종료되도록
  shutdown: graceful
spring:
  autoconfigure:
    exclude:
  lifecycle:
    # 스프링부트가 종료 요청을 받은 후 기다려줄 수 있는 최대한의 시간
    timeout-per-shutdown-phase: 1h
  data:
    redis:
      host: 172.17.0.1
      port: 6379
      password: ON_SECRET
  datasource:
    url: jdbc:mysql://172.17.0.1:3306/tagging_prod
    username: root
    password: ${custom.datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
        highlight_sql: false
        use_sql_comments: false
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
logging:
  level:
    com.ll.tagging-2024-04-19_2: INFO
    org.hibernate.SQL: INFO
    org.hibernate.orm.jdbc.bind: INFO
    org.hibernate.orm.jdbc.extract: INFO
    org.springframework.transaction.interceptor: INFO
custom:
  temp:
    dirPath: /tmp
  gen:
    dirPath: /gen